### PR TITLE
Sl/pre commit hook

### PR DESCRIPTION
**Pull request by sglyon**
This adds a python script I use as a pre-commit to remove all output cells from any notebook in the repo whenever I try to do `git commit`.

I'm not 100% sure I like this. 

On the plus side, it eliminates an annoyance I've had where I open up a notebook to lecture from and all the output is already there. This is annoying because
1. it makes the notebook harder to navigate
2. It doesn't come with any "spoiler alert!" warning -- students can just see exactly what I'm about to tell them
3. Makes the files much larger than they need to be

On the negative side, we can no longer get a preview of any images or results from github or in nbviewer. 

I'm up in the air about this.

Let's have a vote amongst all current and (known) future instructors -- majority wins.

For the record, my vote is **in favor** of this change.

cc @cc7768 @mwaugh0328  @szokeb87 @danielcsaba

### CODE REVIEW

**Comment by cc7768** [comment]
I vote in favor. Nice to not have the punchline spoiled sometimes.

**Comment by szokeb87** [comment]
I vote in favor. I find the advantages convincing

**Comment by danielcsaba** [comment]
Hey guys,
I would also vote in favor.

**Comment by sglyon** [comment]
Done in 92eba499c9b33416c70f8c88809d72614e8a412a

**Pull request closed without merging**
